include: https://gitlab/Sensirion/Python/ci-config-python/raw/master/gitlab-ci-template-v2.yml

check_rst_syntax:
  extends: .check_rst_syntax_v1
  script:
    - rst-lint *.rst

py3p8_64bit_win_build:
  extends: .py3p8_64bit_win_docker_build_v2


build_docs:
  extends: .build_docs_v2


deploy_staging:
  extends: .deploy_staging_v2

deploy_stable:
  extends: .deploy_stable_v2



# Deploy all files within the "public" directory of the artifacts from the jobs
# specified as dependencies. Job must be named pages, otherwise gitlab does
# not deploy to gitlab pages.
pages:
  extends: .deploy_pages_v2
  dependencies: [build_docs]
